version: '3.8'

services:
  app:
    build: .
    container_name: whiteclinic-app
    ports:
      - '3001:3001'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: whiteclinic-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: a123456789
      MYSQL_DATABASE: whiteclinic
      MYSQL_USER: admin
      MYSQL_PASSWORD: a123456789
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  db_data:
