import { industryData } from "./reservationData";

export type RiderData = {
  id: number;
  name: string;
  birth: string;
  loginId: string;
  password: string;
  phone: string;
  address: string;
  detailAddress: string;
  zipcode: string;
  email: string;
  significant: string;
  approval: boolean;
  benefitId: (typeof benefitData)[number]["id"];
  industryId: (typeof industryData)[number]["id"][];
};

export const benefitData: { id: number; benefit: number }[] = [
  { id: 1, benefit: 0.4 },
  { id: 2, benefit: 0.5 },
  { id: 3, benefit: 0.6 },
];

export const ridersData: RiderData[] = [
  {
    id: 1,
    name: "김민수",
    birth: "1995-05-15",
    loginId: "minsu95",
    password: "minsu123!",
    phone: "010-1234-5678",
    address: "서울특별시 강남구",
    detailAddress: "테헤란로 123, 502호",
    zipcode: "06234",
    email: "minsu.kim@example.com",
    significant: "에어컨 전문 자격증 보유, 세탁기 수리 경력 3년",
    approval: true,
    benefitId: 1,
    industryId: [1, 2],
  },
  {
    id: 2,
    name: "이지원",
    birth: "1993-08-22",
    loginId: "jiwon93",
    password: "jiwon456@",
    phone: "010-9876-5432",
    address: "서울특별시 서초구",
    detailAddress: "서초대로 45, 1204호",
    zipcode: "06578",
    email: "jiwon.lee@example.com",
    significant: "세탁기 전문가 자격증 보유, 친절도 우수",
    approval: false,
    benefitId: 2,
    industryId: [1],
  },
  {
    id: 3,
    name: "박성호",
    birth: "1990-12-10",
    loginId: "sungho90",
    password: "park789#",
    phone: "010-2345-6789",
    address: "서울특별시 송파구",
    detailAddress: "올림픽로 78, 304호",
    zipcode: "05540",
    email: "sungho.park@example.com",
    significant: "에어컨 설치 전문가, 10년 경력 보유",
    approval: true,
    benefitId: 3,
    industryId: [2],
  },
  {
    id: 4,
    name: "정다은",
    birth: "1998-03-27",
    loginId: "daeun98",
    password: "jung234$",
    phone: "010-3456-7890",
    address: "서울특별시 마포구",
    detailAddress: "와우산로 159, 801호",
    zipcode: "04068",
    email: "daeun.jung@example.com",
    significant: "가전제품 수리 자격증 다수 보유, 야간 근무 가능",
    approval: false,
    benefitId: 1,
    industryId: [1, 2],
  },
  {
    id: 5,
    name: "최준영",
    birth: "1994-11-05",
    loginId: "junyoung94",
    password: "choi567%",
    phone: "010-4567-8901",
    address: "서울특별시 영등포구",
    detailAddress: "여의대로 128, 1502호",
    zipcode: "07345",
    email: "junyoung.choi@example.com",
    significant: "세탁기 브랜드 공식 수리기사 출신, 꼼꼼한 일처리",
    approval: true,
    benefitId: 2,
    industryId: [1],
  },
  {
    id: 6,
    name: "한미라",
    birth: "1996-07-18",
    loginId: "mira96",
    password: "han890^",
    phone: "010-5678-9012",
    address: "서울특별시 동작구",
    detailAddress: "노량진로 234, 705호",
    zipcode: "06901",
    email: "mira.han@example.com",
    significant: "에어컨 청소 전문가, 고객 만족도 최상위",
    approval: false,
    benefitId: 3,
    industryId: [2],
  },
  {
    id: 7,
    name: "강동훈",
    birth: "1992-09-30",
    loginId: "donghun92",
    password: "kang123&",
    phone: "010-6789-0123",
    address: "서울특별시 광진구",
    detailAddress: "능동로 89, 203호",
    zipcode: "04989",
    email: "donghun.kang@example.com",
    significant: "전자제품 수리 기능사 자격증 보유, 신속한 대응",
    approval: true,
    benefitId: 1,
    industryId: [1, 2],
  },
  {
    id: 8,
    name: "윤서연",
    birth: "1997-01-25",
    loginId: "seoyeon97",
    password: "yoon456*",
    phone: "010-7890-1234",
    address: "서울특별시 성동구",
    detailAddress: "왕십리로 67, 1104호",
    zipcode: "04578",
    email: "seoyeon.yoon@example.com",
    significant: "세탁기 수리 5년 경력, 성실한 근무 태도",
    approval: false,
    benefitId: 2,
    industryId: [1],
  },
  {
    id: 9,
    name: "임현우",
    birth: "1991-04-12",
    loginId: "hyunwoo91",
    password: "lim789@",
    phone: "010-8901-2345",
    address: "서울특별시 용산구",
    detailAddress: "이태원로 156, 402호",
    zipcode: "04351",
    email: "hyunwoo.lim@example.com",
    significant: "에어컨 설치 및 수리 전문가, 주말 근무 선호",
    approval: true,
    benefitId: 3,
    industryId: [2],
  },
  {
    id: 10,
    name: "송지현",
    birth: "1999-06-08",
    loginId: "jihyun99",
    password: "song234#",
    phone: "010-9012-3456",
    address: "서울특별시 종로구",
    detailAddress: "삼일대로 145, 906호",
    zipcode: "03157",
    email: "jihyun.song@example.com",
    significant: "가전제품 종합 수리 가능, 새벽 근무 가능",
    approval: false,
    benefitId: 1,
    industryId: [1, 2],
  },
];

export default ridersData;
